#Tugas Mandiri
**Nama:** Elok Fiola     
**NIM:** 122450051    
**Kelas:** RC

## Nomor 1
Buatlah sebuah program untuk mereduksi fitur menggunakan metode PCA pada dataset berikut ini dengan ketentuan:


In [16]:
#Import library
import numpy as np

In [17]:
#Memasukan data
dt = np.array([
    [2.5, 2.4, 3.1, 1.2, 1.5, 2.3],
    [0.5, 0.7, 1.0, 0.5, 0.3, 0.8],
    [2.2, 2.9, 3.2, 1.4, 1.8, 2.5],
    [1.9, 2.2, 2.5, 1.0, 1.2, 1.8],
    [3.1, 3.6, 4.0, 2.0, 2.5, 3.0],
    [2.3, 2.7, 3.1, 1.7, 1.9, 2.6],
    [2.0, 1.6, 2.3, 0.8, 1.1, 1.5],
    [1.0, 1.1, 1.5, 0.7, 0.9, 1.0],
    [1.5, 1.6, 2.0, 1.3, 1.4, 1.7],
    [1.1, 0.9, 1.3, 0.9, 0.7, 1.0]
])

In [18]:
#menghitung nilai mean dari masing-masing fitur
mean = np.mean(dt, axis=0)
mean

array([1.81, 1.97, 2.4 , 1.15, 1.33, 1.82])

In [19]:
#Lakukan standarisasi
mean = np.mean(dt, axis=0)
std_dev = np.std(dt, axis=0) #axis  0 untuk menghitung rata rata per kolom, kalau baris axis = 1
Z = (dt - mean) / std_dev
print(Z)

[[ 0.92627881  0.47833912  0.76650504  0.11337315  0.28096295  0.6658964 ]
 [-1.7585873  -1.41276904 -1.53301008 -1.47385091 -1.70230494 -1.41502985]
 [ 0.52354889  1.0345474   0.87600576  0.56686573  0.77677993  0.94335323]
 [ 0.12081898  0.25585581  0.10950072 -0.34011944 -0.21485402 -0.02774568]
 [ 1.73173864  1.813239    1.75201152  1.9273435   1.9336862   1.63699531]
 [ 0.6577922   0.81206409  0.76650504  1.24710462  0.94205225  1.08208165]
 [ 0.25506228 -0.41159413 -0.10950072 -0.79361203 -0.38012635 -0.44393093]
 [-1.08737078 -0.96780241 -0.98550648 -1.02035832 -0.710671   -1.13757301]
 [-0.41615425 -0.41159413 -0.43800288  0.34011944  0.11569063 -0.1664741 ]
 [-0.95312747 -1.19028572 -1.20450792 -0.56686573 -1.04121564 -1.13757301]]


In [20]:
#Hitunng matriks kovarians dari Z
cov_matrix = np.cov(Z, rowvar = False)
print(cov_matrix)

[[1.11111111 1.04749839 1.08778066 0.93515901 1.02477917 1.0466329 ]
 [1.04749839 1.11111111 1.09764718 0.99913614 1.06613541 1.0932983 ]
 [1.08778066 1.09764718 1.11111111 0.97384394 1.05970557 1.09036628]
 [0.93515901 0.99913614 0.97384394 1.11111111 1.06803428 1.03455796]
 [1.02477917 1.06613541 1.05970557 1.06803428 1.11111111 1.07353841]
 [1.0466329  1.0932983  1.09036628 1.03455796 1.07353841 1.11111111]]


In [21]:
#Hitung nilai eigen dan vektor eigen dari matriks kovarian cov_matrix
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix) #np.linalg.eig untuk menghitung nilai dan vektor eigen
print("Eigenvalues:") #nilai eigen menggambarkan "kekuatan" atau "pentingnya" dari setiap komponen utama.
print(eigenvalues)
print("Eigenvectors:") #untuk menentukan komponen utama, yaitu arah utama di mana data memiliki variasi terbesar.
print(eigenvectors)

Eigenvalues:
[6.34602953e+00 2.22990199e-01 6.06117738e-02 2.64972963e-02
 5.82468030e-04 9.95539859e-03]
Eigenvectors:
[[-0.40240766 -0.49485365  0.67758552 -0.16735058  0.28205795 -0.16279713]
 [-0.41285937 -0.14960292 -0.57186388  0.19309571  0.29160834 -0.59817759]
 [-0.41323663 -0.34197186 -0.1148881   0.05152103 -0.82934029  0.09290704]
 [-0.39361633  0.73634751  0.22647157 -0.32394094 -0.1958578  -0.32904582]
 [-0.41192263  0.27126387  0.1630848   0.74840833  0.15987602  0.38008372]
 [-0.41501401  0.00153015 -0.35037732 -0.51672105  0.28927832  0.59524295]]


In [22]:
#Hitung proporsi variansi dari nilai eigen
total_variance = np.sum(eigenvalues)
explained_variance_ratio = eigenvalues / total_variance
print("Explained Variance Ratio:")
print(explained_variance_ratio)

Explained Variance Ratio:
[9.51904430e-01 3.34485298e-02 9.09176606e-03 3.97459445e-03
 8.73702045e-05 1.49330979e-03]


In [23]:
#Hitung kontribusi variansi dari nilai eigen
cumulative_variance = np.cumsum(explained_variance_ratio)

#Tampilakn hasil
print("Niali Eigen:", eigenvalues)
print("Proporsi Variasi dari setiap komponen:", explained_variance_ratio)
print("Kontribusi Variasi Kumulatif:", cumulative_variance)

Niali Eigen: [6.34602953e+00 2.22990199e-01 6.06117738e-02 2.64972963e-02
 5.82468030e-04 9.95539859e-03]
Proporsi Variasi dari setiap komponen: [9.51904430e-01 3.34485298e-02 9.09176606e-03 3.97459445e-03
 8.73702045e-05 1.49330979e-03]
Kontribusi Variasi Kumulatif: [0.95190443 0.98535296 0.99444473 0.99841932 0.99850669 1.        ]


In [24]:
#Tentukan ambang batas atau threshold dalam pemilihan nilai eigen
#biasanya di atas 70%
threshold = 0.80 #menjelaskan setidaknya 80% dari total variansi dalam data
n_components = np.argmax(cumulative_variance >= threshold)+ 1
print(n_components) #menampilkan jumlah komponen

1


In [25]:
#Urutkan nilai dan vektor eigen
sorted_indices = np.argsort(eigenvalues)[::-1] #urutkan dari besar ke kecil
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

#tampilkan urutan nilai dan vektor eigen
print("Sorted Eigenvalues:")
print(sorted_eigenvalues)
print("Sorted Eigenvectors:")
print(sorted_eigenvectors)

Sorted Eigenvalues:
[6.34602953e+00 2.22990199e-01 6.06117738e-02 2.64972963e-02
 9.95539859e-03 5.82468030e-04]
Sorted Eigenvectors:
[[-0.40240766 -0.49485365  0.67758552 -0.16735058 -0.16279713  0.28205795]
 [-0.41285937 -0.14960292 -0.57186388  0.19309571 -0.59817759  0.29160834]
 [-0.41323663 -0.34197186 -0.1148881   0.05152103  0.09290704 -0.82934029]
 [-0.39361633  0.73634751  0.22647157 -0.32394094 -0.32904582 -0.1958578 ]
 [-0.41192263  0.27126387  0.1630848   0.74840833  0.38008372  0.15987602]
 [-0.41501401  0.00153015 -0.35037732 -0.51672105  0.59524295  0.28927832]]


In [26]:
#Ambil komponen sesuai n_components sebelumnya.
n_components = 1
W = sorted_eigenvectors[:, :n_components]
print(W) #Vektor ini berfungsi sebagai "basis baru" untuk data, yang memiliki arah variansi terbesar dalam dataset.

[[-0.40240766]
 [-0.41285937]
 [-0.41323663]
 [-0.39361633]
 [-0.41192263]
 [-0.41501401]]


In [27]:
# Lakukan transformasi data
Y = Z @ W # operatoe @ untuk perkalian matriks

# Z adalah data standar
# W adalah matriks yg berisi vektor eigen

In [28]:
#Tampilkan hasil reduksi data PCA
print(Y)

[[-1.32369329]
 [ 3.79304679]
 [-1.934406  ]
 [ 0.03439399]
 [-4.40401192]
 [-2.24472928]
 [ 0.76574005]
 [ 2.41085991]
 [ 0.40594991]
 [ 2.49684984]]


## Soal 2
Buatlah program untuk mereduksi jumlah fitur dari data penyakit jantung di bawah ini dengan ketentuan:
- Gunakan library sklearn
- Pilih komponen utama sebanyak 2.
- Data dapat dimasukkan manual melalui np.array atau langsung menggunakan pd.read_csv() sebelum kemudian mengubahnya kedalam bentuk array menggunakan fungsi pandas dataframe.to_numpy(). Data dapat diunduh pada tautan https://shorturl.at/Dq1OO


In [29]:
#Import pustaka
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [30]:
#Melakukan import data bernama "heart_fitur.csv"
data = pd.read_csv("heart_fitur.csv")
data

age  gender   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   63.0     1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1   67.0     1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2   67.0     1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3   37.0     1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4   63.0     1.0  4.0     130.0  254.0  0.0      2.0    147.0    0.0      1.4   
5   53.0     1.0  4.0     140.0  203.0  1.0      2.0    155.0    1.0      3.1   
6   57.0     1.0  4.0     140.0  192.0  0.0      0.0    148.0    0.0      0.4   
7   56.0     0.0  2.0     140.0  294.0  0.0      2.0    153.0    0.0      1.3   
8   56.0     1.0  3.0     130.0  256.0  1.0      2.0    142.0    1.0      0.6   
9   44.0     1.0  2.0     120.0  263.0  0.0      0.0    173.0    0.0      0.0   
10  52.0     1.0  3.0     172.0  199.0  1.0      0.0    162.0    0.0      0.5   
11  57.0     1.0  3.0     150.0  168.0  0.0      0.0    174.0    0.0      1.6   
12  54.0     1.0  4.0     140.0  239.0  0.0      0.0    160.0    0.0      1.2   
13  48.0     0.0  3.0     130.0  275.0  0.0      0.0    139.0    0.0      0.2   
14  49.0     1.0  2.0     130.0  266.0  0.0      0.0    171.0    0.0      0.6   

    slope   ca  thal  
0     3.0  0.0   6.0  
1     2.0  3.0   3.0  
2     2.0  2.0   7.0  
3     3.0  0.0   3.0  
4     2.0  1.0   7.0  
5     3.0  0.0   7.0  
6     2.0  0.0   6.0  
7     2.0  0.0   3.0  
8     2.0  1.0   6.0  
9     1.0  0.0   7.0  
10    1.0  0.0   7.0  
11    1.0  0.0   3.0  
12    1.0  0.0   3.0  
13    1.0  0.0   3.0  
14    1.0  0.0   3.0

In [31]:
#Mengubah data ke dalam bentuk pandas menggunakan fungsi pandas dataframe.to_numpy()
dataa = data.to_numpy()

In [32]:
# standarisasi data menggunakan StandardScaler dari library sklearn
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
dataa_scaled = scaler.fit_transform(dataa)
print(dataa_scaled)

[[ 1.01155159  0.39223227 -2.22567029  0.47702263 -0.21135989  1.6583124
   1.06904497 -0.16799656 -0.60302269  0.8805602   1.60356745 -0.52764485
   0.57885968]
 [ 1.50903599  0.39223227  1.00514142  1.57222763  1.28891787 -0.60302269
   1.06904497 -2.37295135  1.6583124   0.10926659  0.26726124  2.86435777
  -1.04918318]
 [ 1.50903599  0.39223227  1.00514142 -1.34831905 -0.3245884  -0.60302269
   1.06904497 -1.27047396  1.6583124   1.1697953   0.26726124  1.73369023
   1.12154064]
 [-2.22209695  0.39223227 -0.07179582 -0.61818238  0.26986128 -0.60302269
  -0.93541435  1.77446362 -0.60302269  2.03750061  1.60356745 -0.52764485
  -1.04918318]
 [ 1.01155159  0.39223227  1.00514142 -0.61818238  0.38308979 -0.60302269
   1.06904497 -0.32549333 -0.60302269  0.01285489  0.26726124  0.60302269
   1.12154064]
 [-0.23215938  0.39223227  1.00514142  0.11195429 -1.06057371  1.6583124
   1.06904497  0.09449806  1.6583124   1.65185381  1.60356745 -0.52764485
   1.12154064]
 [ 0.26532501  0.3922322

In [33]:
#Lakukan reduksi dimensi menggunakan PCA dari library sklearn
#DIpilih satu komponen sesuai n_components pada bg.1
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
dataa_pca = pca.fit_transform(dataa_scaled)

In [34]:
#Tampilkan hasil reduksi PCA menggunakan sklearn
print("Data setelah PCA:")
print(dataa_pca)

Data setelah PCA:
[[ 0.95415701 -1.86064443]
 [ 3.87494073  2.51190509]
 [ 3.45834806  0.47107402]
 [-1.80634953 -1.2454564 ]
 [ 1.36694326  0.35705854]
 [ 2.23261405 -2.69525942]
 [-0.48668001 -0.61908021]
 [-0.72343799  2.13173593]
 [ 1.91170781 -0.20478376]
 [-2.40954875  0.14343895]
 [-1.00836399 -1.9805196 ]
 [-1.6320316  -0.92050809]
 [-1.33534801  0.47026055]
 [-2.00785739  2.67368959]
 [-2.38909366  0.76708924]]
